local model = require("scr.battle")
local model_state_machine = require("scr.battle_state_machine")


function init(self)
	-- model.init()
	self.model = model_state_machine.new()
	self.model:start()
end

function on_input(self, action_id, action)

end

function on_message(self, message_id, message, sender)
	self.model:on_message(message_id, message, sender)
	-- model.on_message(message_id, message, sender)
end


