local MN           = require("scr.const.message_names")
local IN           = require("scr.const.input_names")
local settings     = require("scr.settings.game_settings")
local global_urls  = require("scr.const.global_urls")

local REEL_SPACING = 40 -- px between reels

function init(self)
	self.reel_urls = {}

	local pos = go.get_world_position(global_urls.symbols_root())
	local reels_count = settings.slot_machine.default_reels_count
	local start_offset_x = -REEL_SPACING * (reels_count - 1) / 2

	for i = 1, reels_count do
		local x           = (i - 1) * REEL_SPACING
		local spawn_pos   = vmath.vector3(pos.x + x + start_offset_x, pos.y, pos.z - 0.1) -- position each reel
		local ids         = collectionfactory.create(
			"#reel_collectionfactory",
			spawn_pos
		)

		-- collectionfactory.create returns a table { [hashed_id] = hashed_id }
		-- find the root GO of spawned collection by its id suffix
		local root_id     = ids[hash("/root")]
		self.reel_urls[i] = msg.url(nil, root_id, "reel")
	end
end

function on_message(self, message_id, message)
	if message_id == MN.start_spin then
		for _, url in ipairs(self.reel_urls) do
			msg.post(url, MN.start_spin)
		end
	elseif message_id == MN.stop_reel then
		msg.post(self.reel_urls[message.reel_index], MN.stop_reel, {
			reel_index = message.reel_index
		})
	end
end
