local model_prototype = require("scr.slot_machine")
local MN = require("scr.const.message_names")
local IN = require("scr.const.input_names")

local REEL_SPACING = 40 -- px between reels

function init(self)
	msg.post(".", MN.acquire_input_focus)

	self.reel_urls = {}

	local pos = go.get_position(".")
	local reels_count = 3
	local start_offset_x = -REEL_SPACING * (reels_count - 1) / 2

	for i = 1, reels_count do
		local x           = (i - 1) * REEL_SPACING
		local spawn_pos   = vmath.vector3(pos.x + x + start_offset_x, pos.y, pos.z - 0.1) -- position each reel
		local ids         = collectionfactory.create(
			"#reel_collectionfactory",
			spawn_pos
		)

		-- collectionfactory.create returns a table { [hashed_id] = hashed_id }
		-- find the root GO of spawned collection by its id suffix
		local root_id     = ids[hash("/root")]
		self.reel_urls[i] = msg.url(nil, root_id, "reel")
	end

	-- self.model = model_prototype.new(self.reel_urls)
	-- self.model.on_spin_done = function(symbols_apply_data)
	-- 	--TODO: visual effect about strat to apply symbols
	-- end
	self.current_stop = 1 -- which reel player stops next

	-- self.model:spin()
end

function on_input(self, action_id, action)
	-- any tap / Space stops the next unlocked reel in order
	if action_id == IN.STOP_REEL and action.pressed then
		if self.model.spinning and self.current_stop <= #self.reel_urls then
			msg.post(self.reel_urls[self.current_stop], MN.stop_reel, {
				reel_index = self.current_stop,
				reply_to   = msg.url(),
			})
			self.current_stop = self.current_stop + 1
		end
	end
end

function on_message(self, message_id, message)
	if message_id == MN.start_spin then
		for _, url in ipairs(self.reel_urls) do
			msg.post(url, MN.start_spin)
		end
	end
	-- if message_id == MN.reel_stopped then
	-- 	self.model:on_reel_stopped(message)
	-- end
end
