local model           = require("scr.card_tarot")
local MN              = require("scr.const.message_names")
local tweener         = require("tweener.tweener")
local visual_settings = require("scr.settings.visual_settings")
local idle_anim_logic = require("scr.card.card_idle_anim")
local settings        = require("scr.settings.game_settings")

go.property("card_id", hash(""))

local FRONT_URL = "#sprite"
local BACK_URL  = "#back_sprite"

local function get_euler_z(url)
    local q = go.get(url or go.get_id(), "rotation")
    -- quaternion Z-only rotation: angle = 2 * asin(q.z)
    -- but atan2 is more numerically stable:
    local angle_rad = 2 * math.atan2(q.z, q.w)
    return math.deg(angle_rad)
end

local function flip_immediate(self)
    if self.is_facing then
        go.set(BACK_URL, "tint.w", 1)
        go.set(FRONT_URL, "tint.w", 0)
    else
        go.set(BACK_URL, "tint.w", 0)
        go.set(FRONT_URL, "tint.w", 1)
    end

    self.is_facing = not self.is_facing
end

-- flip via tweener instead of manual update
local function flip(self)
    -- if self.anim.flip_state ~= "idle" then return end
    -- self.anim.flip_state = "flipping"

    local duration_half = visual_settings.cards.flip_duration / 2

    tweener.tween(go.EASING_INQUAD, 1, 0, duration_half, function(value, is_end)
        go.set(go.get_id(), "scale.x", value)

        if is_end then
            flip_immediate(self)
            tweener.tween(go.EASING_OUTQUAD, 0, 1, duration_half, function(value, is_end)
                go.set(go.get_id(), "scale.x", value)
            end)
        end
    end)
end

function init(self)
    msg.post(".", MN.acquire_input_focus)

    -- Find the matching card data using the passed hash
    for key, card in pairs(settings.tarot) do
        if hash(card.id) == self.card_id then
            self.card_config = card
            break
        end
    end

    msg.post(FRONT_URL, "play_animation", { id = hash(self.card_config.sprite) })

    idle_anim_logic.init(self, self.card_config.index)

    self.is_facing = true
    flip_immediate(self)
    flip(self)
    -- self.model = model.new()
end

function update(self, dt)
    idle_anim_logic.update(self, dt)
    local rot_deg = get_euler_z()
    idle_anim_logic.apply(self, rot_deg, 1, 1)
end

function on_input(self, action_id, action)
    -- self.model:on_input(action_id, action)
end
