local druid = require("druid.druid")
local MN = require("scr.const.message_names")

function init(self)
    self.druid = druid.new(self)

    self.progress = self.druid:new_progress("damned_progress_fill", "x")
    self.progress:set_to(1)
end

function final(self)
    self.druid:final()
end

function update(self, dt)
    self.druid:update(dt)
end

function on_message(self, message_id, message, sender)
    self.druid:on_message(message_id, message, sender)

    if message_id == MN.set_progress then
        self.progress:set_to(message.value)
    end
end

function on_input(self, action_id, action)
    return self.druid:on_input(action_id, action)
end
